version: "3"
services:
  web:
    build: ./web
    ports:
      - '3000'
    environment:
      PGHOST: database
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: pass

  proxy:
    image: dockercloud/haproxy
    links:
      - web
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: postgres:10
    ports:
      - '5432'
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - './postgres-init:/docker-entrypoint-initdb.d'
